### ISSUE TITLE
Feature: Paths should be globs

### ISSUE THREAD

**Issue by mboudreau** [hexojs/hexo-renderer-less#14]
Using a singular entrypoint which is only a folder is limiting.  I would like the ability to pick and choose which less file(s) are being compiled without compiling all of them.   Using a [library like glob](https://github.com/isaacs/node-glob) will make it much easier to specify multiple files via patterns and recursiveness.

**Comment by curbengh** [comment]
If the files are inside hexo folder (i.e. the folder generated by `hexo init`), then #37 should work.

But #37 globbing doesn't work for node_modules/ and anything outside of hexo folder.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-renderer-less/pull/37
