### ISSUE TITLE
Hexo renderer less prevent the copy of assets recursively

### ISSUE THREAD

**Issue by cbou** [hexojs/hexo-renderer-less#4]
As soon as you install `hexo-renderer-less` into a hexo project, your assets won't be recursively copied.

`hexo init test`
set `post_asset_folder` to `true` in `_config.yml`.
`npm install --save hexo-renderer-less`
`hexo new test`
`mkdir source/_posts/test/photos`
`cp path/to/image.png source/_posts/test/photos`
`hexo generate`

The file `photos/image.png` won't be copied. If you remove the hexo-renderer-less it will.

**Comment by curbengh** [comment]
post_asset_folder works for me in combination with this plugin.
