### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ivanovyordan** [hexojs/hexo-renderer-less#7]
There is difference between the npm package and the code here on line `5` in `index.js` at the npm package. Using the npm package causes `TypeError: Cannot read property 'theme' of undefined
` on `generate`. If you use the GitHub code or remove `this.` from `this.hexo.theme.config.less` everything works fine.

**Comment by vitormargis** [comment]
Had the same problem. Removing de "this" works fine indeed. Thanks.

**Comment by akfish** [comment]
+1 for this.

**Comment by tommy351** [comment]
0.1.3 just published.
